BEGIN TRANSACTION;
DELETE FROM `Account`;
DELETE FROM `RenameType`;
DELETE FROM `AccountType`;
INSERT INTO `RenameType` VALUES (1,'StartsWith');
INSERT INTO `RenameType` VALUES (2,'EndsWith');
INSERT INTO `RenameType` VALUES (3,'Contains');
INSERT INTO `RenameType` VALUES (4,'Is');
INSERT INTO `AccountType` VALUES (2,'Credit Card',NULL,1);
INSERT INTO `AccountType` VALUES (3,'Checking','',1);
INSERT INTO `AccountType` VALUES (4,'Savings','',1);
INSERT INTO `AccountType` VALUES (5,'Cash','',1);
INSERT INTO `AccountType` VALUES (6,'Line of Credit','',1);
INSERT INTO `AccountType` VALUES (7,'Online Payment Account','',1);
INSERT INTO `AccountType` VALUES (8,'Investment Account','',0);
INSERT INTO `AccountType` VALUES (9,'Mortgage','',0);
INSERT INTO `AccountType` VALUES (10,'Asset','',0);
INSERT INTO `AccountType` VALUES (11,'Loan/Liability',NULL,0);
INSERT INTO `Account` VALUES (1,'Citibank Visa',2,0,1,'Probably also better test some special characters </> !--&^%$#@!(');
INSERT INTO `Account` VALUES (2,'Diners MasterCard',2,0,1,'');
INSERT INTO `Account` VALUES (3,'First Bank Checking',3,0,1,'This is a note to test the notes in first bank checking.');
INSERT INTO `Account` VALUES (4,'Paypal',5,0,1,'');
INSERT INTO `Account` VALUES (5,'Roth IRA',7,0,0,'');
INSERT INTO `Account` VALUES (6,'401K',7,0,0,'');
INSERT INTO `Account` VALUES (7,'Cash',4,0,1,'');
INSERT INTO `Account` VALUES (8,'Closed Account',9,1,1,'');
INSERT INTO `Account` VALUES (9,'Closed OffBudget',9,1,0,'');
COMMIT;
